import React, { useEffect } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

import logoPNG from '../public/logo.svg'

export default function Header() {
  const router = useRouter();
    return (
      <React.Fragment>
      <Head>
        <title>Stacked</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='topnav'>

        <div className='topnav-centered'>
          <Link href="/portfolio" passHref>
            <div className={ (router.route=='/portfolio' ? 'hrefdiv active' : 'hrefdiv')}>
              <a>Portfolio</a>
            </div>
          </Link >
          <Link  href="/optimize">
            <a className={ (router.route=='/optimize' ? 'hrefdiv active' : 'hrefdiv')}>Optimization</a>
          </Link >
          <Link  href="/news">
            <a className={ (router.route=='/news' ? 'hrefdiv active' : 'hrefdiv')}>News</a>
          </Link >
        </div>
        
        <a id='navbarlogo' onClick={() => { localStorage.clear(), window.location = "/"}}>
          <div className="logopf">
            <Image src={logoPNG} alt="logo" />
          </div></a>
        
        {/* <div className='topnav-right'>
          <a href='#search'>Search</a>
        </div> */}
      
    </div>
     {/* <div className='header'>
     <p>test</p>
    
  </div> */}
  </React.Fragment>
    )
}